logging:
  level:
    io:
      pivotal: DEBUG
eureka: # <--- ADD NEW SECTION
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}

--- # <--- ADD NEW DOCUMENT

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id}

---  # <--- ADD NEW DOCUMENT

spring:
  profiles: dev
eureka:
  client:    
    serviceUrl:
      defaultZone: https://service-registry-ossicular-buttress.apps.steveb.ed.pcfdemo.com # <-- substitute your service-registry url
